services:
  express:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - dbdata
    networks:
      - backend
    env_file:
      - .env
    environment:
      PORT: 8000
      MONGODB_URL: mongodb://dbdata:27017/ai-linguist

  dbdata:
    image: mongo:8.0
    volumes:
      - dbdata:/data/db
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
