services:
  express:
    container_name: express
    environment:
      NODE_ENV: development
    command: yarn dev -L
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  dbdata:
    ports:
      - '127.0.0.1:27017:27017'
