services:
  express:
    container_name: express
    environment:
      NODE_ENV: test
      MONGODB_URL: mongodb://test:test@dbdata:27017/test-db?authSource=admin
    command: yarn test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - dbdata

  dbdata:
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data-test:/data/db

volumes:
  mongo-data-test:
